export const categoryToGooglePlacesMapping = {
  'AC Service': { type: 'establishment', keywords: 'air conditioning service repair' },
  'Acupuncture': { type: 'health', keywords: 'acupuncture traditional medicine' },
  'Air Duct Cleaning': { type: 'home_service', keywords: 'air duct cleaning ventilation' },
  'Ambulance Service': { type: 'health', keywords: 'emergency medical transport' },
  'Animal Shelters': {type: 'establishment', keywords: 'animal rescue adoption'},
  'Antiques Stores': { type: 'store', keywords: 'antiques collectibles vintage' },
  'Appliance Repair': { type: 'home_service', keywords: 'appliance repair maintenance' },
  'Architects': { type: 'establishment', keywords: 'architect design planning' },
  'Art Galleries': { type: 'art_gallery', keywords: 'art exhibition' },
 'Art Supplies': { type: 'store', keywords: 'art supplies craft' },
  'Astrologers': { type: 'establishment', keywords: 'astrologer fortune teller' },
  'Audio Equipment Store': {type: 'electronics_store', keywords: 'audio equipment speakers sound'},
  'Auto Body Shop': {type: 'car_repair', keywords: 'body repair collision'},
  'Auto Detailing': { type: 'car_wash', keywords: 'car detailing cleaning' },
  'Auto Glass Repair': { type: 'car_repair', keywords: 'windshield glass repair' },
  'Auto Parts': { type: 'car_dealer', keywords: 'auto parts accessories' },
  'Awnings Install & Repair': {type: 'home_service', keywords: 'awnings installation repair'},
  'Baby Stores': { type: 'store', keywords: 'baby products supplies' },
  'Bakeries': { type: 'bakery', keywords: 'bread cakes pastry' },
   'Bakery': { type: 'bakery', keywords: 'bakery pastry' },
  'Banks': { type: 'bank', keywords: 'banking financial services' },
  'Banks & ATMs': { type: 'bank', keywords: 'banking atm' },
  'Bars & Pubs': { type: 'bar', keywords: 'pub tavern' },
  'Battery Shop': {type: 'car_repair', keywords: 'battery sale replacement'},
  'Bed & Breakfast': { type: 'lodging', keywords: 'bed and breakfast accommodation' },
  'Bicycle Shops': { type: 'bicycle_store', keywords: 'bike cycling' },
   'Bike Repair Services': { type: 'bicycle_store', keywords: 'bike repair service' },
  'Blinds & Curtains Store': {type: 'store', keywords:'window blinds curtains shades'},
  'Boarding Schools': { type: 'school', keywords: 'boarding school education' },
  'Bookstores': { type: 'book_store', keywords: 'books stationery' },
   'Boutiques': { type: 'clothing_store', keywords: 'fashion boutique' },
  'Bowling': { type: 'bowling_alley', keywords: 'bowling entertainment' },
   'Brake Services': {type: 'car_repair', keywords: 'brake service repair'},
 'Building Materials': { type: 'hardware_store', keywords: 'construction materials' },
  'Butcher Shops': { type: 'store', keywords: 'butcher meat' },
  'Cafes': { type: 'cafe', keywords: 'coffee shop' },
  'Camera Shops': { type: 'electronics_store', keywords: 'camera photography' },
  'Car Hire': { type: 'car_rental', keywords: 'car hire rental' },
  'Car Repair & Services': { type: 'car_repair', keywords: 'auto service' },
 'Car Wash Services': { type: 'car_wash', keywords: 'car wash cleaning' },
  'Carpet Cleaning': { type: 'home_service', keywords: 'carpet cleaning upholstery' },
  'Cardiologists': { type: 'doctor', keywords: 'heart doctor cardiology' },
  'Caterers': { type: 'food', keywords: 'catering service' },
   'Chauffeur Services': { type: 'car_rental', keywords: 'chauffeur car rental' },
  'Child Care': { type: 'day_care', keywords: 'childcare babysitting' },
 'Children\'s Clothing Stores': { type: 'clothing_store', keywords: 'kids fashion apparel' },
  'Chiropractors': { type: 'chiropractor', keywords: 'chiropractic adjustment' },
  'Churches': { type: 'church', keywords: 'worship religious' },
  'Cinema': { type: 'movie_theater', keywords: 'movies entertainment' },
   'Clothing Stores': { type: 'clothing_store', keywords: 'clothes fashion' },
  'Coaching': { type: 'school', keywords: 'coaching education tutor' },
  'Commercial Cleaning': {type: 'home_service', keywords: 'office cleaning janitorial'},
  'Computer & Laptop Repair & Services': { type: 'electronics_repair', keywords: 'computer laptop repair' },
  'Computer Training Institutes': { type: 'school', keywords: 'computer training education' },
   'Concrete Contractors': {type: 'home_service', keywords: 'concrete pouring repair'},
 'Consultants': { type: 'establishment', keywords: 'consulting business' },
  'Courier Services': { type: 'post_office', keywords: 'courier delivery' },
  'Craft Stores': { type: 'store', keywords: 'craft supplies hobby' },
  'Dance Schools': { type: 'dance_studio', keywords: 'dance instruction' },
  'Day Spas': {type:'spa', keywords: 'day spa relaxation'},
  'Debt Consolidation Services': {type: 'finance', keywords: 'debt management relief'},
  'Department Stores': { type: 'department_store', keywords: 'retail shopping' },
  'Dermatologists': { type: 'doctor', keywords: 'dermatologist skin' },
 'Dentists': { type: 'dentist', keywords: 'dental' },
  'Diagnostic Imaging': {type: 'health', keywords: 'medical imaging radiology'},
   'Digital Marketing Agency': { type: 'establishment', keywords: 'digital marketing seo' },
    'Driving Schools': { type: 'school', keywords: 'driving instruction' },
  'Dry Cleaners': { type: 'laundry', keywords: 'dry cleaning' },
  'Electricians': { type: 'electrician', keywords: 'electrical service' },
   'Embroidery Shop': { type: 'store', keywords: 'embroidery custom apparel'},
  'Employment Agency': {type: 'employment_agency', keywords: 'job placement staffing'},
  'Event Organizer': { type: 'event_venue', keywords: 'event planning' },
  'Eye Care': { type: 'doctor', keywords: 'optometrist ophthalmologist' },
  'Fabricators': { type: 'establishment', keywords: 'metal fabrication welding' },
   'Family Practice': {type: 'doctor', keywords: 'family medicine primary care'},
 'Fast Food Restaurants': { type: 'restaurant', keywords: 'fast food burger fries' },
 'Fencing Contractors': {type: 'home_service', keywords: 'fence installation repair'},
 'Financial Advisor': { type: 'finance', keywords: 'financial planning investment' },
  'Fine Dining Restaurants': { type: 'restaurant', keywords: 'fine dining upscale' },
  'Fireplace Repair': {type: 'home_service', keywords: 'fireplace chimney repair'},
  'Fitness Centers': { type: 'gym', keywords: 'fitness workout' },
  'Floor Installation': {type: 'home_service', keywords: 'floor installation laminate'},
  'Florists': { type: 'florist', keywords: 'flowers bouquet' },
  'Foreign Exchange': { type: 'finance', keywords: 'currency exchange forex' },
  'Furniture Repair Services': { type: 'furniture_store', keywords: 'furniture repair' },
  'Garden Centers': { type: 'store', keywords: 'gardening plants' },
  'Gas Stations': { type: 'gas_station', keywords: 'fuel petrol' },
  'Gastroenterologist': {type: 'doctor', keywords: 'digestive health doctor'},
  'General Stores': { type: 'store', keywords: 'general merchandise variety'},
  'Gift Shops': { type: 'gift_shop', keywords: 'presents souvenirs' },
  'Glass Shop': { type: 'store', keywords: 'glass cutting repair'},
  'Golf Courses': { type: 'golf_course', keywords: 'golf sports' },
  'Gutter Cleaning': { type: 'home_service', keywords: 'gutter cleaning maintenance' },
 'Hair Salons': { type: 'hair_care', keywords: 'hairdresser stylist' },
  'Handyman Services': {type:'home_service', keywords:'home repair maintenance handyman'},
  'Hardware Stores': { type: 'hardware_store', keywords: 'tools equipment' },
  'Hearing Aid Center':{type:'health', keywords:'hearing aid audiology'},
  'Home Appliances': { type: 'electronics_store', keywords: 'appliances white goods' },
  'Home Inspection Services': {type: 'home_service', keywords: 'home inspection property'},
  'Home Renovation Contractors': { type: 'home_service', keywords: 'home renovation remodel' },
    'Home Security': { type: 'establishment', keywords: 'security systems cctv' },
  'Hospitals': { type: 'hospital', keywords: 'medical center' },
   'Hotels': { type: 'lodging', keywords: 'accommodation' },
  'Housekeeping Services': { type: 'home_service', keywords: 'cleaning housekeeping' },
   'Hobbies': { type: 'store', keywords: 'hobby craft' },
  'Indian Restaurants': { type: 'restaurant', keywords: 'Indian food curry biryani' },
 'Insurance Agents': { type: 'insurance_agency', keywords: 'insurance broker' },
  'Interior Designers': { type: 'interior_design', keywords: 'interior designer' },
  'Internet Website Designers': { type: 'establishment', keywords: 'web design development' },
 'Investment Firm': { type: 'finance', keywords: 'investment management' },
  'Italian Restaurants': { type: 'restaurant', keywords: 'Italian food pasta pizza' },
   'Jewellery Showrooms': { type: 'jewelry_store', keywords: 'jewellery' },
'Junk Removal': {type: 'home_service', keywords: 'junk removal cleanout'},
   'Kitchen Remodeling': {type: 'home_service', keywords: 'kitchen renovation remodel'},
  'Landscaping Services': { type: 'home_service', keywords: 'landscaping gardening' },
 'Language Schools': { type: 'school', keywords: 'language learning' },
  'Laundry Services': {type: 'laundry', keywords:'wash dry laundry'},
 'Lawyers': { type: 'lawyer', keywords: 'attorney legal' },
'Leather Repair Shop': { type: 'store', keywords:'leather repair shoes bags'},
  'Libraries': { type: 'library', keywords: 'books reading' },
   'Limousine Services': {type: 'car_rental', keywords: 'limo rental transportation'},
 'Locksmith': { type: 'locksmith', keywords: 'keys security' },
'Luggage Stores': {type: 'store', keywords: 'luggage bags travel'},
  'Marriage Counseling': { type: 'counseling', keywords: 'relationship therapy' },
   'Martial Arts': { type: 'gym', keywords: 'martial arts training' },
   'Mattress Stores': {type: 'store', keywords: 'mattress bed furniture'},
  'Men\'s Clothing Stores': { type: 'clothing_store', keywords: 'men fashion apparel' },
 'Mexican Restaurants': { type: 'restaurant', keywords: 'Mexican food tacos burritos' },
  'Mobile Phone Shops': { type: 'electronics_store', keywords: 'mobile phones repair' },
   'Mortgage Brokers': { type: 'finance', keywords: 'mortgage loans' },
  'Moving Companies': { type: 'moving_company', keywords: 'packers movers relocation' },
  'Museums': { type: 'museum', keywords: 'exhibition culture' },
  'Music Schools': { type: 'school', keywords: 'music lessons' },
 'Musical Instrument Repair': { type: 'store', keywords: 'instrument repair music' },
   'Nail Salons': { type: 'beauty_salon', keywords: 'nail care manicure' },
  'Neurologists': { type: 'doctor', keywords: 'neurologist brain doctor' },
  'Notary': { type: 'lawyer', keywords: 'notary public legal' },
  'Nursing Services': { type: 'health', keywords: 'nursing care' },
  'Office Supplies': { type: 'store', keywords: 'stationery office equipment' },
  'Oncologists': { type: 'doctor', keywords: 'cancer doctor oncology' },
 'Opticians': { type: 'doctor', keywords: 'eyewear optometrist' },
  'Orthopedic Surgeons': {type: 'doctor', keywords: 'bone joint doctor'},
  'Packers & Movers': { type: 'moving_company', keywords: 'packers movers relocation' },
  'Painting Contractors': { type: 'painter', keywords: 'painting contractor' },
  'Party Supplies': { type: 'store', keywords: 'party decoration' },
   'Paving Contractors':{type: 'home_service', keywords: 'paving asphalt driveway'},
    'Pediatricians': { type: 'doctor', keywords: 'child doctor pediatrician' },
 'Pest Control Services': { type: 'establishment', keywords: 'pest control' },
  'Pet Grooming': { type: 'pet_store', keywords: 'pet grooming care' },
   'Pet Shops': { type: 'pet_store', keywords: 'pets supplies' },
  'Pharmacies': { type: 'pharmacy', keywords: 'drugstore medicine' },
 'Photographers': { type: 'photographer', keywords: 'photography studio' },
  'Physiotherapy': { type: 'physiotherapist', keywords: 'physical therapy rehabilitation' },
  'Piano Tuner': { type: 'establishment', keywords: 'piano tuning repair' },
 'Picture Framing': { type: 'store', keywords: 'picture framing art' },
  'Placement Services': { type: 'employment_agency', keywords: 'recruitment placement' },
  'Plumbers': { type: 'plumber', keywords: 'plumbing service' },
   'Podiatrists': { type: 'doctor', keywords: 'foot care podiatry' },
  'Pool Services': { type: 'home_service', keywords: 'swimming pool maintenance' },
 'Pottery Classes': { type: 'school', keywords: 'pottery ceramics' },
   'Printing & Publishing Services': { type: 'printer', keywords: 'printing publishing' },
  'Property Management': { type: 'real_estate_agency', keywords: 'property management' },
  'Psychologists': { type: 'doctor', keywords: 'psychology counseling' },
  'Real Estate': { type: 'real_estate_agency', keywords: 'property' },
  'Registration Consultants': { type: 'establishment', keywords: 'registration consultant' },
  'Restaurants': { type: 'restaurant', keywords: 'dining food' },
 'Roofing': { type: 'roofing_contractor', keywords: 'roof repair' },
  'Scrap Buyers': { type: 'establishment', keywords: 'scrap buyer waste' },
  'Scrap Dealers': { type: 'establishment', keywords: 'scrap dealer recycling' },
  'Security System': { type: 'establishment', keywords: 'security system surveillance' },
   'Septic Tank Service':{type: 'home_service', keywords: 'septic tank cleaning pumping'},
    'Shoe Repair': { type: 'shoe_store', keywords: 'shoe repair' },
 'Sign Shops': { type: 'store', keywords: 'signage custom signs' },
 'Solar Installation': { type: 'establishment', keywords: 'solar panels renewable' },
  'Sports Coaching': { type: 'gym', keywords: 'sports training' },
'Sportswear Stores': { type: 'clothing_store', keywords: 'sportswear activewear' },
   'Storage': { type: 'storage', keywords: 'self storage' },
   'Swimming Pools': { type: 'gym', keywords: 'swimming lessons' },
 'Tailors': { type: 'establishment', keywords: 'tailoring alterations' },
  'Tax Services': { type: 'accounting', keywords: 'tax preparation' },
  'Theater': { type: 'theater', keywords: 'performing arts' },
'Tire Shops': {type: 'car_repair', keywords: 'tire sale repair'} ,
  'Transporters': { type: 'moving_company', keywords: 'transport logistics' },
  'Travel Agencies': { type: 'travel_agency', keywords: 'travel tourism' },
  'Tree Services': { type: 'establishment', keywords: 'tree removal arborist' },
  'Trophy Shops': { type: 'store', keywords: 'trophy awards medals' },
  'Tutoring': { type: 'school', keywords: 'private tutor education' },
   'Upholstery Cleaning': { type: 'home_service', keywords: 'upholstery cleaning' },
 'Vehicle Inspection': { type: 'car_repair', keywords: 'vehicle inspection testing' },
'Veterinarians': { type: 'veterinary_care', keywords: 'vet pet doctor' },
 'Vocational Training': { type: 'school', keywords: 'vocational training skills' },
  'Watch Repair': { type: 'establishment', keywords: 'watch repair jewelry' },
   'Water Delivery': { type: 'establishment', keywords: 'water delivery service' },
  'Waterproofing Services': { type: 'home_service', keywords: 'waterproofing basement' },
'Wedding Planning': { type: 'event_venue', keywords: 'wedding planner' },
  'Wheel Alignment': {type: 'car_repair', keywords:'wheel alignment'},
  'Window Cleaning': { type: 'home_service', keywords: 'window cleaning' },
   'Window Repair': { type: 'home_service', keywords: 'window repair glass' },
  'Wine Shops': { type: 'liquor_store', keywords: 'wine spirits' },
  'Women\'s Clothing Stores': { type: 'clothing_store', keywords: 'women fashion apparel' },
  'Yoga Studios': { type: 'gym', keywords: 'yoga meditation' },
  'General Dentistry': { type: 'dentist', keywords: 'routine dental care checkup' },
  'Cosmetic Dentistry': { type: 'dentist', keywords: 'teeth whitening veneers cosmetic' },
  'Orthodontics': { type: 'dentist', keywords: 'braces aligners orthodontist' },
  'Pediatric Dentistry': { type: 'dentist', keywords: 'children dental care kid dentist' },
  'Endodontics': { type: 'dentist', keywords: 'root canal therapy endodontist' },
   'Periodontics': { type: 'dentist', keywords: 'gum disease treatment periodontist' },
    'Oral Surgery': { type: 'dentist', keywords: 'tooth extraction dental surgery' },
  'Dental Implants': { type: 'dentist', keywords: 'dental implants tooth replacement' },
  'Emergency Dental Care': { type: 'dentist', keywords: 'urgent dental treatment emergency dentist'},
   'Pet Food Supplies': { type: 'pet_store', keywords: 'dog food cat food pet food' },
   'Pet Toys & Accessories': { type: 'pet_store', keywords: 'pet toys leashes collars' },
   'Live Pets Sales': { type: 'pet_store', keywords: 'puppies kittens birds fish' },
   'Aquarium Supplies': { type: 'pet_store', keywords: 'aquarium fish tanks accessories' },
  'Reptile Supplies': { type: 'pet_store', keywords: 'reptile snakes lizards care' },
  'Small Animal Supplies': {type: 'pet_store', keywords: 'hamster guinea pig supplies'},
    'Bird Supplies': { type: 'pet_store', keywords: 'bird food cages accessories' },
   'Pet Grooming Services': { type: 'pet_store', keywords: 'pet grooming dog grooming cat grooming' },
   'Pet Training Supplies': { type: 'pet_store', keywords: 'training collar pet training'},
   'Residential Real Estate': { type: 'real_estate_agency', keywords: 'house apartment condo sale' },
   'Commercial Real Estate': { type: 'real_estate_agency', keywords: 'office retail warehouse lease' },
   'Property Management': { type: 'real_estate_agency', keywords: 'property management rental' },
  'Real Estate Appraisal': { type: 'real_estate_agency', keywords: 'property appraisal valuation' },
  'Real Estate Auction': {type: 'real_estate_agency', keywords: 'property auction foreclosure'},
   'Real Estate Development': {type: 'real_estate_agency', keywords: 'land development building'},
 'Real Estate Investment': {type: 'real_estate_agency', keywords: 'real estate investment property'},
  'Relocation Services': { type: 'real_estate_agency', keywords: 'moving relocation assistance' },
   'Vacation Rentals': { type: 'real_estate_agency', keywords: 'vacation rental holiday home' },
  'Land Sales': {type: 'real_estate_agency', keywords: 'land plots sale property'},
   'Wedding Catering': { type: 'food', keywords: 'wedding catering reception food' },
  'Corporate Catering': { type: 'food', keywords: 'corporate catering event catering' },
  'Private Event Catering': { type: 'food', keywords: 'party catering private event food' },
  'Buffet Catering': { type: 'food', keywords: 'buffet style catering service' },
  'Plated Meal Catering': { type: 'food', keywords: 'plated meal catering fine dining' },
   'Food Truck Catering': { type: 'food', keywords: 'food truck event catering' },
   'Catering Equipment Rental': { type: 'food', keywords: 'catering equipment rental supplies' },
 'Specialty Diet Catering': {type: 'food', keywords: 'vegetarian vegan gluten free catering'},
 'Dessert Catering': {type: 'food', keywords: 'dessert catering cakes pastries'},
'Catering Staffing': {type: 'food', keywords: 'catering staff servers bartenders'},

};