// Add this mapping at the top of placesController.js
export const categoryToGooglePlacesMapping = {
    // Previous categories
    'AC Service': { type: 'establishment', keywords: 'air conditioning service repair' },
    'Astrologers': { type: 'establishment', keywords: 'astrologer fortune teller' },
    'Body Massage Centers': { type: 'spa', keywords: 'massage wellness' },
    'Beauty Spa': { type: 'spa', keywords: 'beauty salon' },
    'Car Hire': { type: 'car_rental', keywords: 'car hire rental' },
    'Caterers': { type: 'food', keywords: 'catering service' },
    'Chartered Accountant': { type: 'accounting', keywords: 'accountant financial' },
    'Computer Training Institutes': { type: 'school', keywords: 'computer training education' },
    'Courier Services': { type: 'post_office', keywords: 'courier delivery' },
    'Computer & Laptop Repair & Services': { type: 'electronics_repair', keywords: 'computer laptop repair' },
    'Car Repair & Services': { type: 'car_repair', keywords: 'auto service' },
    'Dermatologists': { type: 'doctor', keywords: 'dermatologist skin' },
    'Dentists': { type: 'dentist', keywords: 'dental' },
    'Electricians': { type: 'electrician', keywords: 'electrical service' },
    'Event Organizer': { type: 'event_venue', keywords: 'event planning' },
    'Real Estate': { type: 'real_estate_agency', keywords: 'property' },
    'Fabricators': { type: 'establishment', keywords: 'metal fabrication welding' },
    'Furniture Repair Services': { type: 'furniture_store', keywords: 'furniture repair' },
    'Hospitals': { type: 'hospital', keywords: 'medical center' },
    'Housekeeping Services': { type: 'home_service', keywords: 'cleaning housekeeping' },
    'Hobbies': { type: 'store', keywords: 'hobby craft' },
    'Interior Designers': { type: 'interior_design', keywords: 'interior designer' },
    'Internet Website Designers': { type: 'establishment', keywords: 'web design development' },
    'Jewellery Showrooms': { type: 'jewelry_store', keywords: 'jewellery' },
    'Lawyers': { type: 'lawyer', keywords: 'attorney legal' },
    'Transporters': { type: 'moving_company', keywords: 'transport logistics' },
    'Photographers': { type: 'photographer', keywords: 'photography studio' },
    'Nursing Services': { type: 'health', keywords: 'nursing care' },
    'Printing & Publishing Services': { type: 'printer', keywords: 'printing publishing' },
    'Placement Services': { type: 'employment_agency', keywords: 'recruitment placement' },
    'Pest Control Services': { type: 'establishment', keywords: 'pest control' },
    'Painting Contractors': { type: 'painter', keywords: 'painting contractor' },
    'Packers & Movers': { type: 'moving_company', keywords: 'packers movers relocation' },
    'Scrap Dealers': { type: 'establishment', keywords: 'scrap dealer recycling' },
    'Scrap Buyers': { type: 'establishment', keywords: 'scrap buyer waste' },
    'Registration Consultants': { type: 'establishment', keywords: 'registration consultant' },
    'Security System': { type: 'establishment', keywords: 'security system surveillance' },
    'Coaching': { type: 'school', keywords: 'coaching education tutor' },
    'Vocational Training': { type: 'school', keywords: 'vocational training skills' },
    'Acupuncture': { type: 'health', keywords: 'acupuncture traditional medicine' },
    'Art Galleries': { type: 'art_gallery', keywords: 'art exhibition' },
    'Auto Parts': { type: 'car_dealer', keywords: 'auto parts accessories' },
    'Bakery': { type: 'bakery', keywords: 'bakery pastry' },
    'Banks': { type: 'bank', keywords: 'banking financial services' },
    'Bars & Pubs': { type: 'bar', keywords: 'pub tavern' },
    'Bicycle Shops': { type: 'bicycle_store', keywords: 'bike cycling' },
    'Bookstores': { type: 'book_store', keywords: 'books stationery' },
    'Bowling': { type: 'bowling_alley', keywords: 'bowling entertainment' },
    'Building Materials': { type: 'hardware_store', keywords: 'construction materials' },
    'Butcher Shops': { type: 'store', keywords: 'butcher meat' },
    'Cafes': { type: 'cafe', keywords: 'coffee shop' },
    'Camera Shops': { type: 'electronics_store', keywords: 'camera photography' },
    'Carpet Cleaning': { type: 'home_service', keywords: 'carpet cleaning upholstery' },
    'Child Care': { type: 'day_care', keywords: 'childcare babysitting' },
    'Chiropractors': { type: 'chiropractor', keywords: 'chiropractic adjustment' },
    'Churches': { type: 'church', keywords: 'worship religious' },
    'Cinema': { type: 'movie_theater', keywords: 'movies entertainment' },
    'Dance Schools': { type: 'dance_studio', keywords: 'dance instruction' },
    'Department Stores': { type: 'department_store', keywords: 'retail shopping' },
    'Driving Schools': { type: 'school', keywords: 'driving instruction' },
    'Dry Cleaners': { type: 'laundry', keywords: 'dry cleaning' },
    'Eye Care': { type: 'doctor', keywords: 'optometrist ophthalmologist' },
    'Fitness Centers': { type: 'gym', keywords: 'fitness workout' },
    'Florists': { type: 'florist', keywords: 'flowers bouquet' },
    'Foreign Exchange': { type: 'finance', keywords: 'currency exchange forex' },
    'Garden Centers': { type: 'store', keywords: 'gardening plants' },
    'Gas Stations': { type: 'gas_station', keywords: 'fuel petrol' },
    'Gift Shops': { type: 'gift_shop', keywords: 'presents souvenirs' },
    'Golf Courses': { type: 'golf_course', keywords: 'golf sports' },
    'Hair Salons': { type: 'hair_care', keywords: 'hairdresser stylist' },
    'Hardware Stores': { type: 'hardware_store', keywords: 'tools equipment' },
    'Home Appliances': { type: 'electronics_store', keywords: 'appliances white goods' },
    'Home Security': { type: 'establishment', keywords: 'security systems cctv' },
    'Hotels': { type: 'lodging', keywords: 'accommodation' },
    'Insurance Agents': { type: 'insurance_agency', keywords: 'insurance broker' },
    'Language Schools': { type: 'school', keywords: 'language learning' },
    'Libraries': { type: 'library', keywords: 'books reading' },
    'Locksmith': { type: 'locksmith', keywords: 'keys security' },
    'Marriage Counseling': { type: 'counseling', keywords: 'relationship therapy' },
    'Martial Arts': { type: 'gym', keywords: 'martial arts training' },
    'Mobile Phone Shops': { type: 'electronics_store', keywords: 'mobile phones repair' },
    'Mortgage Brokers': { type: 'finance', keywords: 'mortgage loans' },
    'Museums': { type: 'museum', keywords: 'exhibition culture' },
    'Music Schools': { type: 'school', keywords: 'music lessons' },
    'Nail Salons': { type: 'beauty_salon', keywords: 'nail care manicure' },
    'Notary': { type: 'lawyer', keywords: 'notary public legal' },
    'Office Supplies': { type: 'store', keywords: 'stationery office equipment' },
    'Opticians': { type: 'doctor', keywords: 'eyewear optometrist' },
    'Party Supplies': { type: 'store', keywords: 'party decoration' },
    'Pet Grooming': { type: 'pet_store', keywords: 'pet grooming care' },
    'Pet Shops': { type: 'pet_store', keywords: 'pets supplies' },
    'Pharmacies': { type: 'pharmacy', keywords: 'drugstore medicine' },
    'Physiotherapy': { type: 'physiotherapist', keywords: 'physical therapy rehabilitation' },
    'Piano Tuner': { type: 'establishment', keywords: 'piano tuning repair' },
    'Plumbers': { type: 'plumber', keywords: 'plumbing service' },
    'Podiatrists': { type: 'doctor', keywords: 'foot care podiatry' },
    'Pool Services': { type: 'home_service', keywords: 'swimming pool maintenance' },
    'Pottery Classes': { type: 'school', keywords: 'pottery ceramics' },
    'Property Management': { type: 'real_estate_agency', keywords: 'property management' },
    'Psychologists': { type: 'doctor', keywords: 'psychology counseling' },
    'Restaurants': { type: 'restaurant', keywords: 'dining food' },
    'Roofing': { type: 'roofing_contractor', keywords: 'roof repair' },
    'Shoe Repair': { type: 'shoe_store', keywords: 'shoe repair' },
    'Solar Installation': { type: 'establishment', keywords: 'solar panels renewable' },
    'Sports Coaching': { type: 'gym', keywords: 'sports training' },
    'Storage': { type: 'storage', keywords: 'self storage' },
    'Swimming Pools': { type: 'gym', keywords: 'swimming lessons' },
    'Tailors': { type: 'establishment', keywords: 'tailoring alterations' },
    'Tax Services': { type: 'accounting', keywords: 'tax preparation' },
    'Theater': { type: 'theater', keywords: 'performing arts' },
    'Travel Agencies': { type: 'travel_agency', keywords: 'travel tourism' },
    'Tree Services': { type: 'establishment', keywords: 'tree removal arborist' },
    'Tutoring': { type: 'school', keywords: 'private tutor education' },
    'Vehicle Inspection': { type: 'car_repair', keywords: 'vehicle inspection testing' },
    'Veterinarians': { type: 'veterinary_care', keywords: 'vet pet doctor' },
    'Watch Repair': { type: 'establishment', keywords: 'watch repair jewelry' },
    'Water Delivery': { type: 'establishment', keywords: 'water delivery service' },
    'Wedding Planning': { type: 'event_venue', keywords: 'wedding planner' },
    'Window Cleaning': { type: 'home_service', keywords: 'window cleaning' },
    'Wine Shops': { type: 'liquor_store', keywords: 'wine spirits' },
    'Yoga Studios': { type: 'gym', keywords: 'yoga meditation' }
  };